### ISSUE TITLE
TileLayer problem

### ISSUE THREAD

**Issue by warrenalphonso** [BramCetusAlt/Stellar-Arena#1]
A window opens up and I can browser instructions and the 3 worlds. Once I click a world, nothing happens and my terminal prints out: `AttributeError: 'TileLayer' object has no attribute 'data'`.  Any ideas on how to fix?

**Comment by 0xL0WK3Y** [comment]
The problem probably comes from a version mismatch of the pytiled-parser library. The problem with arcade is that it is not backwards compatible so in order to run the game you need arcade 2.1.6 which is the version it was developed in. If you have another version I recommend uninstalling it and installing all the dependencies manually and then arcade 2.1.6. I do recommend following the steps I have written on the Installation section of the README. 

If it does not work, feel free to notify me and thank you for your comment.

> 
> 
> A window opens up and I can browser instructions and the 3 worlds. Once I click a world, nothing happens and my terminal prints out: `AttributeError: 'TileLayer' object has no attribute 'data'`. Any ideas on how to fix?

**Comment by warrenalphonso** [comment]
<img width="697" alt="Screen Shot 2020-12-03 at 8 48 15 AM" src="https://user-images.githubusercontent.com/38018861/101060466-4cf36580-3544-11eb-876e-97558fd59ea7.png">

Thanks for the quick reply! I've created a virtual environment so that it's easy to see my pip packages. Does everything look correct? 

Personally, I don't think it's a dependency problem and instead something wrong with the `.tmx` Tiled Map Editor files. Whenever you get time, can you try making a fresh clone of the repo and running `python StellarArena.py`? If it works for you right after cloning then I'll know it isn't something wrong with the files itself.

**Comment by 0xL0WK3Y** [comment]
Everything looks correct. I don't think it is a problem with the files since they work fine on my side the problem has to be with one of the dependencies. Are you running Python 3.7 or Python 3.9? Arcade is a very fragile library with little backwards compatibility so it could be a problem with 3.9. I am getting an error in 3.9 too but not in 3.7.

**Comment by warrenalphonso** [comment]
I'm on Python version 3.7.3. I've got no idea what could be wrong. Just to be sure, you've cloned it yourself into a new repo and everything works fine?

**Comment by 0xL0WK3Y** [comment]
Yes it works fine on my end and but I've heard a few other people having the same issue you do. For others, however, it runs fine. I don't know what's missing but I will try to figure it out.

**Comment by 0xL0WK3Y** [comment]
I fixed the issue. Like I said the problem with arcade is that it has several issues with dependency and backwards compatibility. It seems like when you install arcade==2.1.6 it automatically downloads the newest version of pytiled-parser (currently 0.9.4) which is not compatible with arcade version 2.1.6. The solution is to do `pip uninstall pytiled-parser` and then `pip install pytiled-parser==0.9.3`.

**Comment by warrenalphonso** [comment]
It worked! Thanks for solving this.

**Comment by 0xL0WK3Y** [comment]
Thank you for bringing this to my attention, friend!
